project_id = "qeevcauhornyqrfeevwc"

[functions.generate-coupon]
verify_jwt = true

[functions.redeem-coupon]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = true

[functions.mercadopago-checkout]
verify_jwt = true

[functions.mercadopago-webhook]
verify_jwt = false
